[parity]
chain = "simvoni-spec.json"
base_path = "$HOME/openethereum-node"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "parity_accounts"]
[websockets]
port = 8450
[account]
password = ["node.pwds"]